general {
    # Не запускать второй hyprlock, если он уже открыт
    lock_cmd = pidof hyprlock || hyprlock

    # Перед сном залочить сессию
    before_sleep_cmd = loginctl lock-session

    # После пробуждения включить экран
    after_sleep_cmd = hyprctl dispatch dpms on

    # Нормальный режим ожидания перед сном
    inhibit_sleep = 3
}

# Через 5 минут — заблокировать экран
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Через 6 минут — выключить экран
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Через 15 минут — сон
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
