general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
    fractional_scaling = 2
    fail_timeout = 1500
}

auth {
    pam:enabled = true
    pam:module = hyprlock
}

animations {
    enabled = true
}

background {
    monitor =
    path = screenshot
    color = rgba(10, 12, 18, 1.0)

    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.9
    brightness = 0.55
    vibrancy = 0.25
    vibrancy_darkness = 0.15
}

label {
    monitor =
    text = $TIME
    color = rgba(202, 231, 255, 1.0)
    font_size = 86
    font_family = JetBrainsMono Nerd Font
    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.65)

    position = 0, 130
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%a %d %b %Y"
    color = rgba(180, 205, 225, 0.95)
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    shadow_passes = 2
    shadow_size = 3
    shadow_color = rgba(0, 0, 0, 0.55)

    position = 0, 65
    halign = center
    valign = center
}

shape {
    monitor =
    size = 420, 86
    color = rgba(8, 14, 24, 0.50)
    rounding = 20
    border_size = 1
    border_color = rgba(90, 170, 255, 0.35)

    position = 0, -82
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 340, 54
    outline_thickness = 2

    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    dots_rounding = -1

    outer_color = rgba(90, 170, 255, 0.85)
    inner_color = rgba(10, 20, 32, 0.72)
    font_color = rgba(220, 235, 255, 1.0)

    check_color = rgba(120, 190, 255, 0.9)
    fail_color = rgba(255, 85, 105, 0.95)
    fail_text = <i>$FAIL</i>

    placeholder_text = <span foreground="##b4cde1">Введите пароль...</span>

    fade_on_empty = false
    hide_input = false
    rounding = 14

    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(0, 0, 0, 0.55)

    position = 0, -82
    halign = center
    valign = center
}

label {
    monitor =
    text =   $USER
    color = rgba(180, 205, 225, 0.85)
    font_size = 16
    font_family = JetBrainsMono Nerd Font

    position = 0, -145
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT
    color = rgba(180, 205, 225, 0.65)
    font_size = 13
    font_family = JetBrainsMono Nerd Font

    position = 0, -175
    halign = center
    valign = center
}
